#-*- coding: utf-8 -*-

{
	"name": "ProductRequest",
	"version": "1.0", 
	"depends": [
		'base','purchase','sale','stock',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the ProductRequest module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/product_request.xml",
		"data/sequence_product_request.xml",
		"view/request_detail.xml",
		"view/product.xml", #inherited
		"view/stock_location.xml", #inherited
		"view/transfer.xml", #inherited
		"view/po.xml", #inherited
		"report/product_request.xml",
		"report/request_detail.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}