#-*- coding: utf-8 -*-

{
	"name": "ProductRequest Inherited",
	"version": "1.0", 
	"depends": [
		'base','purchase','sale','stock',
		'vit_product_request'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the ProductRequest module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"view/product_request.xml",
		"security/groups.xml",
		# "data/sequence_product_request.xml",
		# "view/request_detail.xml",
		# "view/product.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}